

<div id="ymc-icons-modal" class="ymc-icons-modal" style="display:none;">

	<div id="term-settings" class="term-settings">

		<div class="tabs">
			<div class="tab tab-icons active">
				<span class="tab-inner" data-content="<?php esc_attr_e('icon'); ?>">
					<?php esc_html_e('Icon Settings','ymc-smart-filter'); ?></span>
			</div>
			<div class="tab tab-terms">
				<span class="tab-inner" data-content="<?php esc_attr_e('term'); ?>">
					<?php esc_html_e('Tag Settings','ymc-smart-filter'); ?></span>
			</div>
		</div>

		<div class="btn-setting-wrp">
			<a href="#" class="btn-apply"><?php esc_html_e('Apply', 'ymc-smart-filter'); ?></a>
		</div>

		<div class="ymc-icons-content">
			<label class="info">
				<?php echo esc_html__('Add icon. Set the color, location of the selected icon.','ymc-smart-filter'); ?>
			</label>
			<div class="panel-setting">
				<input class="search-icon" type="search" name="search-icon" placeholder="Search icon...">
				<div class="color-icon">
					<input class="ymc-custom-color ymc-icon-color" type="text" name='ymc-icon-color' value="#000000" />
				</div>
				<div class="align-icon">
					<a class="toggle-align-icon" href="#" data-align="left-icon" title="Align Left">
						<i class="fas fa-align-left"></i>
						<span class="note"><?php _e('Saved','ymc-smart-filter'); ?></span>
					</a>
					<a class="toggle-align-icon" href="#" data-align="right-icon" title="Align Right">
						<i class="fas fa-align-right"></i>
						<span class="note"><?php _e('Saved','ymc-smart-filter'); ?></span>
					</a>
				</div>
				<span class="preview-icon"></span>
				<a class="remove-link" href="#" title="Remove Icon">
					<i class="fas fa-trash icon-trash"></i>
				</a>
			</div>
			<div class="icons-entry">
				<i class="far fa-window-restore"></i>
				<i class="far fa-window-minimize"></i>
				<i class="far fa-window-maximize"></i>
				<i class="far fa-window-close"></i>
				<i class="far fa-user-circle"></i>
				<i class="far fa-user"></i>
				<i class="far fa-trash-alt"></i>
				<i class="far fa-tired"></i>
				<i class="far fa-times-circle"></i>
				<i class="far fa-thumbs-up"></i>
				<i class="far fa-thumbs-down"></i>
				<i class="far fa-surprise"></i>
				<i class="far fa-sun"></i>
				<i class="far fa-stop-circle"></i>
				<i class="far fa-sticky-note"></i>
				<i class="far fa-star-half"></i>
				<i class="far fa-star"></i>
				<i class="far fa-square"></i>
				<i class="far fa-snowflake"></i>
				<i class="far fa-smile-wink"></i>
				<i class="far fa-smile-beam"></i>
				<i class="far fa-smile"></i>
				<i class="far fa-share-square"></i>
				<i class="far fa-save"></i>
				<i class="far fa-sad-tear"></i>
				<i class="far fa-sad-cry"></i>
				<i class="far fa-registered"></i>
				<i class="far fa-question-circle"></i>
				<i class="far fa-plus-square"></i>
				<i class="far fa-play-circle"></i>
				<i class="far fa-pause-circle"></i>
				<i class="far fa-paper-plane"></i>
				<i class="far fa-object-ungroup"></i>
				<i class="far fa-object-group"></i>
				<i class="far fa-newspaper"></i>
				<i class="far fa-moon"></i>
				<i class="far fa-money-bill-alt"></i>
				<i class="far fa-minus-square"></i>
				<i class="far fa-meh-rolling-eyes"></i>
				<i class="far fa-meh-blank"></i>
				<i class="far fa-meh"></i>
				<i class="far fa-map"></i>
				<i class="far fa-list-alt"></i>
				<i class="far fa-lightbulb"></i>
				<i class="far fa-life-ring"></i>
				<i class="far fa-lemon"></i>
				<i class="far fa-laugh-wink"></i>
				<i class="far fa-laugh-squint"></i>
				<i class="far fa-laugh-beam"></i>
				<i class="far fa-laugh"></i>
				<i class="far fa-kiss-wink-heart"></i>
				<i class="far fa-kiss-beam"></i>
				<i class="far fa-kiss"></i>
				<i class="far fa-keyboard"></i>
				<i class="far fa-images"></i>
				<i class="far fa-image"></i>
				<i class="far fa-id-card"></i>
				<i class="far fa-id-badge"></i>
				<i class="far fa-hourglass"></i>
				<i class="far fa-hospital"></i>
				<i class="far fa-heart"></i>
				<i class="far fa-hdd"></i>
				<i class="far fa-handshake"></i>
				<i class="far fa-hand-spock"></i>
				<i class="far fa-hand-scissors"></i>
				<i class="far fa-hand-rock"></i>
				<i class="far fa-hand-scissors"></i>
				<i class="far fa-hand-rock"></i>
				<i class="far fa-hand-pointer"></i>
				<i class="far fa-hand-point-up"></i>
				<i class="far fa-hand-point-right"></i>
				<i class="far fa-hand-point-left"></i>
				<i class="far fa-hand-point-down"></i>
				<i class="far fa-hand-peace"></i>
				<i class="far fa-gem"></i>
				<i class="far fa-futbol"></i>
				<i class="far fa-folder-open"></i>
				<i class="far fa-folder"></i>
				<i class="far fa-flushed"></i>
				<i class="far fa-flag"></i>
				<i class="far fa-file-word"></i>
				<i class="far fa-file-video"></i>
				<i class="far fa-file-powerpoint"></i>
				<i class="far fa-file-pdf"></i>
				<i class="far fa-file-image"></i>
				<i class="far fa-file-excel"></i>
				<i class="far fa-file-code"></i>
				<i class="far fa-file-audio"></i>
				<i class="far fa-file-archive"></i>
				<i class="far fa-file-alt"></i>
				<i class="far fa-file"></i>
				<i class="far fa-eye-slash"></i>
				<i class="far fa-eye"></i>
				<i class="far fa-envelope-open"></i>
				<i class="far fa-envelope"></i>
				<i class="far fa-edit"></i>
				<i class="far fa-dot-circle"></i>
				<i class="far fa-dizzy"></i>
				<i class="far fa-credit-card"></i>
				<i class="far fa-copyright"></i>
				<i class="far fa-copy"></i>
				<i class="far fa-compass"></i>
				<i class="far fa-comments"></i>
				<i class="far fa-comment-dots"></i>
				<i class="far fa-comment-alt"></i>
				<i class="far fa-comment"></i>
				<i class="far fa-closed-captioning"></i>
				<i class="far fa-clone"></i>
				<i class="far fa-clock"></i>
				<i class="far fa-clipboard"></i>
				<i class="far fa-circle"></i>
				<i class="far fa-check-square"></i>
				<i class="far fa-check-circle"></i>
				<i class="far fa-chart-bar"></i>
				<i class="far fa-caret-square-up"></i>
				<i class="far fa-caret-square-right"></i>
				<i class="far fa-caret-square-left"></i>
				<i class="far fa-caret-square-down"></i>
				<i class="far fa-calendar-times"></i>
				<i class="far fa-calendar-plus"></i>
				<i class="far fa-calendar-minus"></i>
				<i class="far fa-calendar-check"></i>
				<i class="far fa-calendar-alt"></i>
				<i class="far fa-calendar"></i>
				<i class="far fa-building"></i>
				<i class="far fa-bookmark"></i>
				<i class="far fa-bell-slash"></i>
				<i class="far fa-bell"></i>
				<i class="far fa-arrow-alt-circle-up"></i>
				<i class="far fa-arrow-alt-circle-right"></i>
				<i class="far fa-arrow-alt-circle-left"></i>
				<i class="far fa-arrow-alt-circle-down"></i>
				<i class="far fa-angry"></i>
				<i class="far fa-address-card"></i>
				<i class="far fa-address-book"></i>
				<i class="fas fa-yin-yang"></i>
				<i class="fas fa-yen-sign"></i>
				<i class="fas fa-wrench"></i>
				<i class="fas fa-wine-glass-alt"></i>
				<i class="fas fa-wine-glass"></i>
				<i class="fas fa-wine-bottle"></i>
				<i class="fas fa-window-restore"></i>
				<i class="fas fa-window-minimize"></i>
				<i class="fas fa-window-maximize"></i>
				<i class="fas fa-window-close"></i>
				<i class="fas fa-wifi"></i>
				<i class="fas fa-wheelchair"></i>
				<i class="fas fa-weight-hanging"></i>
				<i class="fas fa-weight"></i>
				<i class="fas fa-wave-square"></i>
				<i class="fas fa-water"></i>
				<i class="fas fa-warehouse"></i>
				<i class="fas fa-wallet"></i>
				<i class="fas fa-walking"></i>
				<i class="fas fa-vr-cardboard"></i>
				<i class="fas fa-vote-yea"></i>
				<i class="fas fa-volume-up"></i>
				<i class="fas fa-volume-off"></i>
				<i class="fas fa-volume-mute"></i>
				<i class="fas fa-volume-down"></i>
				<i class="fas fa-volleyball-ball"></i>
				<i class="fas fa-voicemail"></i>
				<i class="fas fa-viruses"></i>
				<i class="fas fa-virus-slash"></i>
				<i class="fas fa-virus"></i>
				<i class="fas fa-vihara"></i>
				<i class="fas fa-video-slash"></i>
				<i class="fas fa-video"></i>
				<i class="fas fa-vials"></i>
				<i class="fas fa-vial"></i>
				<i class="fas fa-venus-mars"></i>
				<i class="fas fa-venus-double"></i>
				<i class="fas fa-venus"></i>
				<i class="fas fa-vector-square"></i>
				<i class="fas fa-utensils"></i>
				<i class="fas fa-utensil-spoon"></i>
				<i class="fas fa-users-cog"></i>
				<i class="fas fa-users"></i>
				<i class="fas fa-user-times"></i>
				<i class="fas fa-user-tie"></i>
				<i class="fas fa-user-tag"></i>
				<i class="fas fa-user-slash"></i>
				<i class="fas fa-user-shield"></i>
				<i class="fas fa-user-secret"></i>
				<i class="fas fa-user-plus"></i>
				<i class="fas fa-user-nurse"></i>
				<i class="fas fa-user-ninja"></i>
				<i class="fas fa-user-minus"></i>
				<i class="fas fa-user-md"></i>
				<i class="fas fa-user-lock"></i>
				<i class="fas fa-user-graduate"></i>
				<i class="fas fa-user-friends"></i>
				<i class="fas fa-user-edit"></i>
				<i class="fas fa-user-cog"></i>
				<i class="fas fa-user-clock"></i>
				<i class="fas fa-user-circle"></i>
				<i class="fas fa-user-check"></i>
				<i class="fas fa-user-astronaut"></i>
				<i class="fas fa-user-alt-slash"></i>
				<i class="fas fa-user-alt"></i>
				<i class="fas fa-user"></i>
				<i class="fas fa-upload"></i>
				<i class="fas fa-unlock-alt"></i>
				<i class="fas fa-unlock"></i>
				<i class="fas fa-unlink"></i>
				<i class="fas fa-university"></i>
				<i class="fas fa-universal-access"></i>
				<i class="fas fa-undo-alt"></i>
				<i class="fas fa-undo"></i>
				<i class="fas fa-underline"></i>
				<i class="fas fa-umbrella-beach"></i>
				<i class="fas fa-umbrella"></i>
				<i class="fas fa-tv"></i>
				<i class="fas fa-tty"></i>
				<i class="fas fa-tshirt"></i>
				<i class="fas fa-truck-pickup"></i>
				<i class="fas fa-truck-moving"></i>
				<i class="fas fa-truck-monster"></i>
				<i class="fas fa-truck-loading"></i>
				<i class="fas fa-truck"></i>
				<i class="fas fa-trophy"></i>
				<i class="fas fa-tree"></i>
				<i class="fas fa-trash-restore-alt"></i>
				<i class="fas fa-trash-restore"></i>
				<i class="fas fa-trash-alt"></i>
				<i class="fas fa-trash"></i>
				<i class="fas fa-transgender-alt"></i>
				<i class="fas fa-transgender"></i>
				<i class="fas fa-tram"></i>
				<i class="fas fa-train"></i>
				<i class="fas fa-trailer"></i>
				<i class="fas fa-traffic-light"></i>
				<i class="fas fa-trademark"></i>
				<i class="fas fa-tractor"></i>
				<i class="fas fa-torii-gate"></i>
				<i class="fas fa-torah"></i>
				<i class="fas fa-tooth"></i>
				<i class="fas fa-tools"></i>
				<i class="fas fa-toolbox"></i>
				<i class="fas fa-toggle-on"></i>
				<i class="fas fa-toggle-off"></i>
				<i class="fas fa-tired"></i>
				<i class="fas fa-tint-slash"></i>
				<i class="fas fa-tint"></i>
				<i class="fas fa-times-circle"></i>
				<i class="fas fa-times"></i>
				<i class="fas fa-ticket-alt"></i>
				<i class="fas fa-thumbtack"></i>
				<i class="fas fa-thumbs-up"></i>
				<i class="fas fa-thumbs-down"></i>
				<i class="fas fa-thermometer-three-quarters"></i>
				<i class="fas fa-thermometer-quarter"></i>
				<i class="fas fa-thermometer-half"></i>
				<i class="fas fa-thermometer-full"></i>
				<i class="fas fa-thermometer-empty"></i>
				<i class="fas fa-thermometer"></i>
				<i class="fas fa-theater-masks"></i>
				<i class="fas fa-th-list"></i>
				<i class="fas fa-th-large"></i>
				<i class="fas fa-th"></i>
				<i class="fas fa-text-width"></i>
				<i class="fas fa-text-height"></i>
				<i class="fas fa-terminal"></i>
				<i class="fas fa-temperature-low"></i>
				<i class="fas fa-temperature-high"></i>
				<i class="fas fa-teeth-open"></i>
				<i class="fas fa-teeth"></i>
				<i class="fas fa-taxi"></i>
				<i class="fas fa-tasks"></i>
				<i class="fas fa-tape"></i>
				<i class="fas fa-tags"></i>
				<i class="fas fa-tag"></i>
				<i class="fas fa-tachometer-alt"></i>
				<i class="fas fa-tablets"></i>
				<i class="fas fa-tablet-alt"></i>
				<i class="fas fa-tablet"></i>
				<i class="fas fa-table-tennis"></i>
				<i class="fas fa-table"></i>
				<i class="fas fa-syringe"></i>
				<i class="fas fa-sync-alt"></i>
				<i class="fas fa-sync"></i>
				<i class="fas fa-synagogue"></i>
				<i class="fas fa-swimmer"></i>
				<i class="fas fa-swatchbook"></i>
				<i class="fas fa-surprise"></i>
				<i class="fas fa-superscript"></i>
				<i class="fas fa-sun"></i>
				<i class="fas fa-suitcase-rolling"></i>
				<i class="fas fa-suitcase"></i>
				<i class="fas fa-subway"></i>
				<i class="fas fa-subscript"></i>
				<i class="fas fa-stroopwafel"></i>
				<i class="fas fa-street-view"></i>
				<i class="fas fa-stream"></i>
				<i class="fas fa-store-slash"></i>
				<i class="fas fa-store"></i>
				<i class="fas fa-stopwatch-20"></i>
				<i class="fas fa-stopwatch"></i>
				<i class="fas fa-stop-circle"></i>
				<i class="fas fa-stop"></i>
				<i class="fas fa-sticky-note"></i>
				<i class="fas fa-stethoscope"></i>
				<i class="fas fa-step-forward"></i>
				<i class="fas fa-step-backward"></i>
				<i class="fas fa-star-of-life"></i>
				<i class="fas fa-star-of-david"></i>
				<i class="fas fa-star-half-alt"></i>
				<i class="fas fa-star-and-crescent"></i>
				<i class="fas fa-star"></i>
				<i class="fas fa-stamp"></i>
				<i class="fas fa-square-root-alt"></i>
				<i class="fas fa-spray-can"></i>
				<i class="fas fa-spinner"></i>
				<i class="fas fa-spider"></i>
				<i class="fas fa-spell-check"></i>
				<i class="fas fa-space-shuttle"></i>
				<i class="fas fa-spa"></i>
				<i class="fas fa-sort-numeric-up"></i>
				<i class="fas fa-sort-numeric-down-alt"></i>
				<i class="fas fa-sort-numeric-down"></i>
				<i class="fas fa-sort-amount-up-alt"></i>
				<i class="fas fa-sort-amount-up"></i>
				<i class="fas fa-sort-amount-down-alt"></i>
				<i class="fas fa-sort-amount-down"></i>
				<i class="fas fa-sort-alpha-up-alt"></i>
				<i class="fas fa-sort-alpha-up"></i>
				<i class="fas fa-sort-alpha-down-alt"></i>
				<i class="fas fa-sort-alpha-down"></i>
				<i class="fas fa-sort"></i>
				<i class="fas fa-solar-panel"></i>
				<i class="fas fa-socks"></i>
				<i class="fas fa-soap"></i>
				<i class="fas fa-snowplow"></i>
				<i class="fas fa-snowman"></i>
				<i class="fas fa-snowflake"></i>
				<i class="fas fa-snowboarding"></i>
				<i class="fas fa-sms"></i>
				<i class="fas fa-smoking-ban"></i>
				<i class="fas fa-smoking"></i>
				<i class="fas fa-smog"></i>
				<i class="fas fa-smile-wink"></i>
				<i class="fas fa-smile-beam"></i>
				<i class="fas fa-smile"></i>
				<i class="fas fa-sliders-h"></i>
				<i class="fas fa-sleigh"></i>
				<i class="fas fa-skull-crossbones"></i>
				<i class="fas fa-skull"></i>
				<i class="fas fa-sitemap"></i>
				<i class="fas fa-sink"></i>
				<i class="fas fa-sim-card"></i>
				<i class="fas fa-signal"></i>
				<i class="fas fa-sign-out-alt"></i>
				<i class="fas fa-sign-language"></i>
				<i class="fas fa-sign-in-alt"></i>
				<i class="fas fa-sign"></i>
				<i class="fas fa-shuttle-van"></i>
				<i class="fas fa-shower"></i>
				<i class="fas fa-shopping-cart"></i>
				<i class="fas fa-shopping-basket"></i>
				<i class="fas fa-shopping-bag"></i>
				<i class="fas fa-shoe-prints"></i>
				<i class="fas fa-shipping-fast"></i>
				<i class="fas fa-ship"></i>
				<i class="fas fa-shield-virus"></i>
				<i class="fas fa-shield-alt"></i>
				<i class="fas fa-shekel-sign"></i>
				<i class="fas fa-share-square"></i>
				<i class="fas fa-share-alt-square"></i>
				<i class="fas fa-share-alt"></i>
				<i class="fas fa-share"></i>
				<i class="fas fa-shapes"></i>
				<i class="fas fa-server"></i>
				<i class="fas fa-seedling"></i>
				<i class="fas fa-search-plus"></i>
				<i class="fas fa-search-minus"></i>
				<i class="fas fa-search-location"></i>
				<i class="fas fa-search-dollar"></i>
				<i class="fas fa-search"></i>
				<i class="fas fa-sd-card"></i>
				<i class="fas fa-scroll"></i>
				<i class="fas fa-screwdriver"></i>
				<i class="fas fa-school"></i>
				<i class="fas fa-save"></i>
				<i class="fas fa-satellite-dish"></i>
				<i class="fas fa-satellite"></i>
				<i class="fas fa-running"></i>
				<i class="fas fa-ruler-vertical"></i>
				<i class="fas fa-ruler-horizontal"></i>
				<i class="fas fa-ruler-combined"></i>
				<i class="fas fa-ruble-sign"></i>
				<i class="fas fa-rss-square"></i>
				<i class="fas fa-rss"></i>
				<i class="fas fa-rocket"></i>
				<i class="fas fa-robot"></i>
				<i class="fas fa-road"></i>
				<i class="fas fa-ring"></i>
				<i class="fas fa-ribbon"></i>
				<i class="fas fa-retweet"></i>
				<i class="fas fa-restroom"></i>
				<i class="fas fa-reply-all"></i>
				<i class="fas fa-reply"></i>
				<i class="fas fa-remove-format"></i>
				<i class="fas fa-registered"></i>
				<i class="fas fa-redo-alt"></i>
				<i class="fas fa-redo"></i>
				<i class="fas fa-recycle"></i>
				<i class="fas fa-record-vinyl"></i>
				<i class="fas fa-receipt"></i>
				<i class="fas fa-random"></i>
				<i class="fas fa-rainbow"></i>
				<i class="fas fa-radiation-alt"></i>
				<i class="fas fa-radiation"></i>
				<i class="fas fa-quran"></i>
				<i class="fas fa-quote-right"></i>
				<i class="fas fa-quote-left"></i>
				<i class="fas fa-quidditch"></i>
				<i class="fas fa-question-circle"></i>
				<i class="fas fa-question"></i>
				<i class="fas fa-qrcode"></i>
				<i class="fas fa-puzzle-piece"></i>
				<i class="fas fa-pump-soap"></i>
				<i class="fas fa-pump-medical"></i>
				<i class="fas fa-project-diagram"></i>
				<i class="fas fa-procedures"></i>
				<i class="fas fa-print"></i>
				<i class="fas fa-praying-hands"></i>
				<i class="fas fa-pray"></i>
				<i class="fas fa-power-off"></i>
				<i class="fas fa-pound-sign"></i>
				<i class="fas fa-portrait"></i>
				<i class="fas fa-poop"></i>
				<i class="fas fa-poo-storm"></i>
				<i class="fas fa-poo"></i>
				<i class="fas fa-poll-h"></i>
				<i class="fas fa-poll"></i>
				<i class="fas fa-podcast"></i>
				<i class="fas fa-plus-square"></i>
				<i class="fas fa-plus-circle"></i>
				<i class="fas fa-plus"></i>
				<i class="fas fa-plug"></i>
				<i class="fas fa-play-circle"></i>
				<i class="fas fa-play"></i>
				<i class="fas fa-plane-slash"></i>
				<i class="fas fa-plane-departure"></i>
				<i class="fas fa-plane-arrival"></i>
				<i class="fas fa-plane"></i>
				<i class="fas fa-place-of-worship"></i>
				<i class="fas fa-pizza-slice"></i>
				<i class="fas fa-pills"></i>
				<i class="fas fa-piggy-bank"></i>
				<i class="fas fa-photo-video"></i>
				<i class="fas fa-phone-volume"></i>
				<i class="fas fa-phone-square-alt"></i>
				<i class="fas fa-phone-square"></i>
				<i class="fas fa-phone-slash"></i>
				<i class="fas fa-phone-alt"></i>
				<i class="fas fa-phone"></i>
				<i class="fas fa-person-booth"></i>
				<i class="fas fa-percentage"></i>
				<i class="fas fa-percent"></i>
				<i class="fas fa-pepper-hot"></i>
				<i class="fas fa-people-carry"></i>
				<i class="fas fa-people-arrows"></i>
				<i class="fas fa-pencil-ruler"></i>
				<i class="fas fa-pencil-alt"></i>
				<i class="fas fa-pen-square"></i>
				<i class="fas fa-highlighter"></i>
				<i class="fas fa-helicopter"></i>
				<i class="fas fa-heartbeat"></i>
				<i class="fas fa-heart"></i>
				<i class="fas fa-headset"></i>
				<i class="fas fa-headphones-alt"></i>
				<i class="fas fa-headphones"></i>
				<i class="fas fa-heading"></i>
				<i class="fas fa-head-side-virus"></i>
				<i class="fas fa-head-side-mask"></i>
				<i class="fas fa-head-side-cough"></i>
				<i class="fas fa-hdd"></i>
				<i class="fas fa-hat-cowboy"></i>
				<i class="fas fa-hashtag"></i>
				<i class="fas fa-hard-hat"></i>
				<i class="fas fa-hanukiah"></i>
				<i class="fas fa-handshake-slash"></i>
				<i class="fas fa-handshake-alt-slash"></i>
				<i class="fas fa-handshake"></i>
				<i class="fas fa-hands"></i>
				<i class="fas fa-hand-point-up"></i>
				<i class="fas fa-hand-point-right"></i>
				<i class="fas fa-hand-point-left"></i>
				<i class="fas fa-hand-point-down"></i>
				<i class="fas fa-hand-peace"></i>
				<i class="fas fa-hand-holding-water"></i>
				<i class="fas fa-hand-holding-usd"></i>
				<i class="fas fa-hand-holding-medical"></i>
				<i class="fas fa-hand-holding-heart"></i>
				<i class="fas fa-hand-holding"></i>
				<i class="fas fa-hamsa"></i>
				<i class="fas fa-hammer"></i>
				<i class="fas fa-hamburger"></i>
				<i class="fas fa-h-square"></i>
				<i class="fas fa-guitar"></i>
				<i class="fas fa-grip-vertical"></i>
				<i class="fas fa-grip-lines-vertical"></i>
				<i class="fas fa-grip-lines"></i>
				<i class="fas fa-grip-horizontal"></i>
				<i class="fas fa-greater-than-equal"></i>
				<i class="fas fa-greater-than"></i>
				<i class="fas fa-graduation-cap"></i>
				<i class="fas fa-globe-europe"></i>
				<i class="fas fa-globe-asia"></i>
				<i class="fas fa-globe-americas"></i>
				<i class="fas fa-globe-africa"></i>
				<i class="fas fa-globe"></i>
				<i class="fas fa-glasses"></i>
				<i class="fas fa-glass-whiskey"></i>
				<i class="fas fa-glass-martini-alt"></i>
				<i class="fas fa-genderless"></i>
				<i class="fas fa-gem"></i>
				<i class="fas fa-gavel"></i>
				<i class="fas fa-gas-pump"></i>
				<i class="fas fa-gamepad"></i>
				<i class="fas fa-futbol"></i>
				<i class="fas fa-funnel-dollar"></i>
				<i class="fas fa-frog"></i>
				<i class="fas fa-folder-plus"></i>
				<i class="fas fa-folder-open"></i>
				<i class="fas fa-folder-minus"></i>
				<i class="fas fa-folder"></i>
				<i class="fas fa-flag-usa"></i>
				<i class="fas fa-flag-checkered"></i>
				<i class="fas fa-flag"></i>
				<i class="fas fa-fish"></i>
				<i class="fas fa-first-aid"></i>
				<i class="fas fa-fire-extinguisher"></i>
				<i class="fas fa-fire-alt"></i>
				<i class="fas fa-fire"></i>
				<i class="fas fa-fingerprint"></i>
				<i class="fas fa-file-word"></i>
				<i class="fas fa-file-video"></i>
				<i class="fas fa-file-upload"></i>
				<i class="fas fa-file-signature"></i>
				<i class="fas fa-file-prescription"></i>
				<i class="fas fa-file-powerpoint"></i>
				<i class="fas fa-file-pdf"></i>
				<i class="fas fa-file-medical-alt"></i>
				<i class="fas fa-file-medical"></i>
				<i class="fas fa-file-invoice-dollar"></i>
				<i class="fas fa-file-invoice"></i>
				<i class="fas fa-file-import"></i>
				<i class="fas fa-file-image"></i>
				<i class="fas fa-file-export"></i>
				<i class="fas fa-file-excel"></i>
				<i class="fas fa-file-download"></i>
				<i class="fas fa-file-csv"></i>
				<i class="fas fa-file-contract"></i>
				<i class="fas fa-file-code"></i>
				<i class="fas fa-file-audio"></i>
				<i class="fas fa-file-archive"></i>
				<i class="fas fa-file-alt"></i>
				<i class="fas fa-file"></i>
				<i class="fas fa-fighter-jet"></i>
				<i class="fas fa-female"></i>
				<i class="fas fa-feather-alt"></i>
				<i class="fas fa-feather"></i>
				<i class="fas fa-fax"></i>
				<i class="fas fa-faucet"></i>
				<i class="fas fa-fan"></i>
				<i class="fas fa-eye-dropper"></i>
				<i class="fas fa-eye"></i>
				<i class="fas fa-external-link-square-alt"></i>
				<i class="fas fa-external-link-alt"></i>
				<i class="fas fa-expand-arrows-alt"></i>
				<i class="fas fa-expand-alt"></i>
				<i class="fas fa-expand"></i>
				<i class="fas fa-exclamation-triangle"></i>
				<i class="fas fa-exclamation-circle"></i>
				<i class="fas fa-exclamation"></i>
				<i class="fas fa-exchange-alt"></i>
				<i class="fas fa-euro-sign"></i>
				<i class="fas fa-envelope-square"></i>
				<i class="fas fa-envelope-open-text"></i>
				<i class="fas fa-envelope-open"></i>
				<i class="fas fa-envelope"></i>
				<i class="fas fa-ellipsis-v"></i>
				<i class="fas fa-ellipsis-h"></i>
				<i class="fas fa-drum-steelpan"></i>
				<i class="fas fa-drum"></i>
				<i class="fas fa-draw-polygon"></i>
				<i class="fas fa-drafting-compass"></i>
				<i class="fas fa-download"></i>
				<i class="fas fa-dove"></i>
				<i class="fas fa-dot-circle"></i>
				<i class="fas fa-donate"></i>
				<i class="fas fa-dolly-flatbed"></i>
				<i class="fas fa-dolly"></i>
				<i class="fas fa-dollar-sign"></i>
				<i class="fas fa-dog"></i>
				<i class="fas fa-dna"></i>
				<i class="fas fa-dice"></i>
				<i class="fas fa-dharmachakra"></i>
				<i class="fas fa-desktop"></i>
				<i class="fas fa-database"></i>
				<i class="fas fa-cut"></i>
				<i class="fas fa-cubes"></i>
				<i class="fas fa-cube"></i>
				<i class="fas fa-crutch"></i>
				<i class="fas fa-crown"></i>
				<i class="fas fa-crow"></i>
				<i class="fas fa-crosshairs"></i>
				<i class="fas fa-cross"></i>
				<i class="fas fa-couch"></i>
				<i class="fas fa-copyright"></i>
				<i class="fas fa-copy"></i>
				<i class="fas fa-cookie-bite"></i>
				<i class="fas fa-cookie"></i>
				<i class="fas fa-concierge-bell"></i>
				<i class="fas fa-compress-arrows-alt"></i>
				<i class="fas fa-compass"></i>
				<i class="fas fa-compact-disc"></i>
				<i class="fas fa-comments-dollar"></i>
				<i class="fas fa-comment"></i>
				<i class="fas fa-coins"></i>
				<i class="fas fa-cogs"></i>
				<i class="fas fa-cog"></i>
				<i class="fas fa-coffee"></i>
				<i class="fas fa-code-branch"></i>
				<i class="fas fa-cloud-upload-alt"></i>
				<i class="fas fa-cloud-sun-rain"></i>
				<i class="fas fa-cloud-sun"></i>
				<i class="fas fa-cloud-showers-heavy"></i>
				<i class="fas fa-cloud-rain"></i>
				<i class="fas fa-cloud-moon-rain"></i>
				<i class="fas fa-cloud-moon"></i>
				<i class="fas fa-cloud-meatball"></i>
				<i class="fas fa-clock"></i>
				<i class="fas fa-clipboard-list"></i>
				<i class="fas fa-clipboard-check"></i>
				<i class="fas fa-clipboard"></i>
				<i class="fas fa-clinic-medical"></i>
				<i class="fas fa-circle-notch"></i>
				<i class="fas fa-circle"></i>
				<i class="fas fa-child"></i>
				<i class="fas fa-chevron-up"></i>
				<i class="fas fa-chevron-right"></i>
				<i class="fas fa-chevron-left"></i>
				<i class="fas fa-chevron-down"></i>
				<i class="fas fa-chevron-circle-up"></i>
				<i class="fas fa-chevron-circle-right"></i>
				<i class="fas fa-chevron-circle-left"></i>
				<i class="fas fa-chevron-circle-down"></i>
				<i class="fas fa-chess-rook"></i>
				<i class="fas fa-chess-queen"></i>
				<i class="fas fa-chess-pawn"></i>
				<i class="fas fa-chess-knight"></i>
				<i class="fas fa-chess-king"></i>
				<i class="fas fa-chess-board"></i>
				<i class="fas fa-chess-bishop"></i>
				<i class="fas fa-chess"></i>
				<i class="fas fa-check-square"></i>
				<i class="fas fa-check-double"></i>
				<i class="fas fa-check-circle"></i>
				<i class="fas fa-check"></i>
				<i class="fas fa-chart-pie"></i>
				<i class="fas fa-chart-line"></i>
				<i class="fas fa-chart-bar"></i>
				<i class="fas fa-charging-station"></i>
				<i class="fas fa-chalkboard-teacher"></i>
				<i class="fas fa-chalkboard"></i>
				<i class="fas fa-chair"></i>
				<i class="fas fa-certificate"></i>
				<i class="fas fa-cat"></i>
				<i class="fas fa-cash-register"></i>
				<i class="fas fa-cart-plus"></i>
				<i class="fas fa-cart-arrow-down"></i>
				<i class="fas fa-carrot"></i>
				<i class="fas fa-caravan"></i>
				<i class="fas fa-car-side"></i>
				<i class="fas fa-car-crash"></i>
				<i class="fas fa-car-battery"></i>
				<i class="fas fa-car-alt"></i>
				<i class="fas fa-car"></i>
				<i class="fas fa-capsules"></i>
				<i class="fas fa-cannabis"></i>
				<i class="fas fa-candy-cane"></i>
				<i class="fas fa-campground"></i>
				<i class="fas fa-camera-retro"></i>
				<i class="fas fa-camera"></i>
				<i class="fas fa-calendar-week"></i>
				<i class="fas fa-calendar-alt"></i>
				<i class="fas fa-calendar-check"></i>
				<i class="fas fa-calculator"></i>
				<i class="fas fa-business-time"></i>
				<i class="fas fa-bus-alt"></i>
				<i class="fas fa-bus"></i>
				<i class="fas fa-burn"></i>
				<i class="fas fa-bullseye"></i>
				<i class="fas fa-bullhorn"></i>
				<i class="fas fa-building"></i>
				<i class="fas fa-bug"></i>
				<i class="fas fa-brush"></i>
				<i class="fas fa-briefcase-medical"></i>
				<i class="fas fa-briefcase"></i>
				<i class="fas fa-bowling-ball"></i>
				<i class="fas fa-border-style"></i>
				<i class="fas fa-border-none"></i>
				<i class="fas fa-border-all"></i>
				<i class="fas fa-bookmark"></i>
				<i class="fas fa-book-reader"></i>
				<i class="fas fa-book-open"></i>
				<i class="fas fa-book-medical"></i>
				<i class="fas fa-book-dead"></i>
				<i class="fas fa-book"></i>
				<i class="fas fa-bong"></i>
				<i class="fas fa-bone"></i>
				<i class="fas fa-bomb"></i>
				<i class="fas fa-bolt"></i>
				<i class="fas fa-bold"></i>
				<i class="fas fa-blog"></i>
				<i class="fas fa-blind"></i>
				<i class="fas fa-blender-phone"></i>
				<i class="fas fa-blender"></i>
				<i class="fas fa-birthday-cake"></i>
				<i class="fas fa-biohazard"></i>
				<i class="fas fa-binoculars"></i>
				<i class="fas fa-biking"></i>
				<i class="fas fa-bicycle"></i>
				<i class="fas fa-bible"></i>
				<i class="fas fa-bezier-curve"></i>
				<i class="fas fa-bell-slash"></i>
				<i class="fas fa-bell"></i>
				<i class="fas fa-beer"></i>
				<i class="fas fa-bed"></i>
				<i class="fas fa-battery-three-quarters"></i>
				<i class="fas fa-battery-quarter"></i>
				<i class="fas fa-battery-half"></i>
				<i class="fas fa-battery-full"></i>
				<i class="fas fa-battery-empty"></i>
				<i class="fas fa-bath"></i>
				<i class="fas fa-basketball-ball"></i>
				<i class="fas fa-baseball-ball"></i>
				<i class="fas fa-bars"></i>
				<i class="fas fa-barcode"></i>
				<i class="fas fa-band-aid"></i>
				<i class="fas fa-ban"></i>
				<i class="fas fa-balance-scale-right"></i>
				<i class="fas fa-balance-scale-left"></i>
				<i class="fas fa-balance-scale"></i>
				<i class="fas fa-bahai"></i>
				<i class="fas fa-bacterium"></i>
				<i class="fas fa-bacteria"></i>
				<i class="fas fa-bacon"></i>
				<i class="fas fa-backspace"></i>
				<i class="fas fa-baby-carriage"></i>
				<i class="fas fa-baby"></i>
				<i class="fas fa-award"></i>
				<i class="fas fa-audio-description"></i>
				<i class="fas fa-atom"></i>
				<i class="fas fa-atlas"></i>
				<i class="fas fa-at"></i>
				<i class="fas fa-asterisk"></i>
				<i class="fas fa-arrows-alt-v"></i>
				<i class="fas fa-arrows-alt-h"></i>
				<i class="fas fa-arrows-alt"></i>
				<i class="fas fa-arrow-up"></i>
				<i class="fas fa-arrow-right"></i>
				<i class="fas fa-arrow-left"></i>
				<i class="fas fa-arrow-down"></i>
				<i class="fas fa-arrow-circle-up"></i>
				<i class="fas fa-arrow-circle-right"></i>
				<i class="fas fa-arrow-circle-left"></i>
				<i class="fas fa-arrow-circle-down"></i>
				<i class="fas fa-apple-alt"></i>
				<i class="fas fa-ankh"></i>
				<i class="fas fa-angle-double-up"></i>
				<i class="fas fa-angle-double-right"></i>
				<i class="fas fa-angle-double-left"></i>
				<i class="fas fa-angle-double-down"></i>
				<i class="fas fa-anchor"></i>
				<i class="fas fa-american-sign-language-interpreting"></i>
				<i class="fas fa-ambulance"></i>
				<i class="fas fa-align-right"></i>
				<i class="fas fa-align-left"></i>
				<i class="fas fa-align-justify"></i>
				<i class="fas fa-align-center"></i>
				<i class="fas fa-air-freshener"></i>
				<i class="fas fa-adjust"></i>
				<i class="fas fa-address-book"></i>
				<i class="fas fa-ad"></i>
			</div>
		</div>

		<div class="ymc-terms-content ymc-hidden">
			<label class="info">
				<?php echo esc_html__('Set the background, color, name class of the selected term.','ymc-smart-filter'); ?>
			</label>
			<div class="terms-entry">
				<div class="form-element">
					<label class="form-label">
						<?php esc_html_e('Background', 'ymc-smart-filter'); ?>
						<span class="information">
                            <?php echo esc_html__('Set tag background .', 'ymc-smart-filter');?>
                        </span>
					</label>
					<input class="ymc-custom-color ymc-term-bg" type="text" name='ymc-term-bg' value=""/>
				</div>
				<div class="form-element">
					<label class="form-label">
						<?php esc_html_e('Color', 'ymc-smart-filter'); ?>
						<span class="information">
                            <?php echo esc_html__('Set color tag.', 'ymc-smart-filter');?>
                        </span>
					</label>
					<input class="ymc-custom-color ymc-term-color" type="text"  name='ymc-term-color' value=""/>
				</div>
				<div class="form-element">
					<label class="form-label">
						<?php esc_html_e('Class', 'ymc-smart-filter'); ?>
						<span class="information">
                            <?php echo esc_html__('Set custom class tag.', 'ymc-smart-filter');?>
                        </span>
					</label>
					<input class="input-field ymc-term-class" type="text" name="ymc-term-class" placeholder="Custom class for tag" value="" />
				</div>
				<div class="form-element">
					<label class="form-label">
						<?php esc_html_e('Default Tag', 'ymc-smart-filter'); ?>
						<span class="information">
                            <?php echo esc_html__('Set the tag to default while posts load on frontend. For standard plugin Filter Layouts except for the Alphabetical Layout.', 'ymc-smart-filter');?>
                        </span>
					</label>
					<input class="input-field ymc-term-default" id="ymc-term-default" type="checkbox" name="ymc-term-default" value="checked" />
					<label for="ymc-term-default"><?php esc_html_e('Enable', 'ymc-smart-filter'); ?></label>
				</div>
				<div class="form-element">
					<label class="form-label">
						<?php esc_html_e('Name', 'ymc-smart-filter'); ?>
						<span class="information">
                            <?php echo esc_html__('Set a custom tag name. To restore the default tag name, clear the field.', 'ymc-smart-filter');?>
                        </span>
					</label>
					<input class="input-field ymc-term-custom-name" type="text" name="ymc-term-custom-name" placeholder="Term custom name" value="" />
				</div>
			</div>
		</div>

	</div>

</div>